update_frequency: 5
# obstacles:
  # - {type: sample_camera, motion_type: static, position: "[[1, 0.5], [1.5, 0.7], [2.5,1.5]]", stdev: 0.02} //
  # - {type: robot_camera, motion_type: reciprocation, position: "[[1, 0.5], [2.5, 2]]", stdev: 0.01}
  # - {type: robot_tracker, motion_type: reciprocation, position: "[[1, 0.5], [2.5, 2]]", stdev: 0.01} //
  # - {type: robot_lidar, motion_type: static, position: "[[1, 0.5], [1.5, 0.7], [2.5,1.5]]", stdev: 0.02}

obstacles:
  - {type: sample_camera, motion_type: static, position: "[[0.575, 0.225],[0.775, 0.225],[1.075, 0.725],[2.225, 1.775],
            [2.425, 1.775],[1.875, 0.725],[2.225, 0.225],[2.425, 0.225],[1.875, 1.275]]", stdev: 0.01}
  # - {type: robot_camera, motion_type: reciprocation, position: "[[1, 0.5], [2.5, 2]]", stdev: 0.01}

# obstacles2:
#   - {type: sample_camera, motion_type: static, position: "[[2.225, 1.775],[2.425, 1.775]]", stdev: 0.02}
#   # - {type: robot_camera, motion_type: reciprocation, position: "[[1, 0.5], [2.5, 2]]", stdev: 0.01}

# obstacles3:
#   - {type: sample_camera, motion_type: static, position: "[[2.225, 0.225],[2.425, 0.225]]", stdev: 0.02}
#   # - {type: robot_camera, motion_type: reciprocation, position: "[[1, 0.5], [2.5, 2]]", stdev: 0.01}

# 
#   |---------------  3  --------------|
#   |                                  |
#   |                                  |
#   |                                  |
#   |                                  |
#   | ---                           ---|
#   |                                  |
#   |                                  |
#   |                                  |
#   |                                  |
#   1  ------------------------------  2
# 
# 