# # route1
# - xyz: [1.15, 1.75, 1]
# - xyz: [1.15, 1.75, 1]
# - xyz: [0.6, 1.75, 2]
# - xyz: [1.15, 1.25, 1]
# - xyz: [0.25, 0.25, 1]
# - xyz: [2.8, 1.3, 1]
# - xyz: [0.5, 1, 1]
# - xyz: [1, 1, 1]
# - xyz: [1, 0.225, 1]
# - xyz: [1.5, 1.5, 1]
# - xyz: [1.5, 0.9, 1]

# # route2
# - xyz: [2.7, 0.5, 1]
# - xyz: [2.7, 0.5, 1]
# - xyz: [0.3, 0.5, 0.75]
# - xyz: [2.7, 0.5, 1]
# - xyz: [0.3, 0.5, 1]
# - xyz: [2.7, 0.5, 1]

# route3
- xyz: [2.7, 0.2, 1]
- xyz: [2.7, 0.2, 1]
- xyz: [2.7, 1.8, 1]
- xyz: [2.7, 0.2, 0.75]
- xyz: [2.7, 1.8, 1]
- xyz: [2.7, 0.2, 1]
- xyz: [2.7, 1.8, 1]

# # route4
# - xyz: [0.447, 1.21, 1]
# - xyz: [0.542, 1.168, 1]
# - xyz: [0.542, 1.168, 1]
# - xyz: [0.447, 1.21, 1]

# # route5
# - xyz: [0.2, 0.192, 1]
# - xyz: [0.2, 0.192, 1]
# - xyz: [2.8, 0.192, 1]

# # route6
# - xyz: [1.5, 0.52, 1]
# - xyz: [1.5, 0.52, 1]
